const config = {
	spellcheck: false,
	placeholderText: '이곳에 적어주세요',
	editorClass: 'editorContainer',
	width: '100%',
	charCounterCount: false,
	tabSpaces: 8,
	toolbarInline: true,
	toolbarVisibleWithoutSelection: true,
	colorsDefaultTab: 'background',
	colorsBackground: ['#FFFAA5', '#9BDBFF', '#FF3466', 'REMOVE'],
	colorsText: ['#FFFAA5', '#9BDBFF', '#FF3466', 'REMOVE'],
	toolbarButtonsMD: [
		'bold',
		'color',
		'italic',
		'underline',
		'paragraphFormat',
		'align',
		'formatOL',
		'formatUL',
		'outdent',
		'indent',
		'insertLink',
		'insertHR',
		'print',
		'insertTable',
	],
	toolbarButtonsSM: [
		'bold',
		'color',
		'italic',
		'underline',
		'paragraphFormat',
		'align',
		'formatOL',
		'formatUL',
		'outdent',
		'indent',
		'insertLink',
		'insertHR',
		'print',
		'insertTable',
	],
	toolbarButtonsXS: [
		'bold',
		'color',
		'italic',
		'underline',
		'paragraphFormat',
		'align',
		'formatOL',
		'formatUL',
		'outdent',
		'indent',
		'insertLink',
		'insertHR',
		'print',
		'insertTable',
	],
	toolbarButtons: [
		'bold',
		'color',
		'italic',
		'underline',
		'paragraphFormat',
		'align',
		'formatOL',
		'formatUL',
		'outdent',
		'indent',
		'insertLink',
		'insertHR',
		'print',
		'insertTable',
	],
	paragraphFormat: {
		N: 'Normal',
		H4: 'Code',
		H3: 'Head 3',
		H2: 'Head 2',
		H1: 'Head 1',
	},
};

export default config;
