const config = {
	spellcheck: false,
	placeholderText: '',
	editorClass: 'editorContainer',
	width: '100%',
	charCounterCount: false,
	tabSpaces: 8,
	toolbarInline: true,
	pluginsEnabled: ['colors', 'lists', 'paragraphFormat', 'quote'],
	shortcutsEnabled: ['paragraphFormat'],
	pastePlain: true,
	toolbarVisibleWithoutSelection: true,
	colorsDefaultTab: 'background',
	colorsBackground: ['#FFFAA5', '#9BDBFF', '#FF3466', 'REMOVE'],
	colorsText: ['#FFFAA5', '#9BDBFF', '#FF3466', 'REMOVE'],
	toolbarButtonsMD: [
		'bold',
		'color',
		'italic',
		'underline',
		'paragraphFormat',
		'align',
		'formatOL',
		'formatUL',
		'outdent',
		'indent',
		'insertLink',
		'print',
		'quote',
	],
	toolbarButtonsSM: [
		'bold',
		'color',
		'italic',
		'underline',
		'paragraphFormat',
		'align',
		'formatOL',
		'formatUL',
		'outdent',
		'indent',
		'insertLink',
		'quote',
		'print',
	],
	toolbarButtonsXS: [
		'bold',
		'color',
		'italic',
		'underline',
		'paragraphFormat',
		'align',
		'formatOL',
		'formatUL',
		'outdent',
		'indent',
		'insertLink',
		'quote',
		'insertTable',
	],
	toolbarButtons: [
		'bold',
		'color',
		'italic',
		'underline',
		'paragraphFormat',
		'align',
		'formatOL',
		'formatUL',
		'outdent',
		'indent',
		'insertLink',
		'print',
		'quote',
		'insertTable',
	],
	paragraphFormat: {
		N: 'Normal',
		PRE: 'Code',
		H3: 'H3',
		H2: 'H2',
		H1: 'H1',
	},
};

export default config;
