// flow-typed signature: 5a65cbf603e9b6544cfad4af32c3c935
// flow-typed version: <<STUB>>/hangul-js_v^0.2.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hangul-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hangul-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hangul-js/Gruntfile' {
  declare module.exports: any;
}

declare module 'hangul-js/hangul' {
  declare module.exports: any;
}

declare module 'hangul-js/hangul.min' {
  declare module.exports: any;
}

declare module 'hangul-js/test/index' {
  declare module.exports: any;
}

declare module 'hangul-js/test/server-side' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hangul-js/Gruntfile.js' {
  declare module.exports: $Exports<'hangul-js/Gruntfile'>;
}
declare module 'hangul-js/hangul.js' {
  declare module.exports: $Exports<'hangul-js/hangul'>;
}
declare module 'hangul-js/hangul.min.js' {
  declare module.exports: $Exports<'hangul-js/hangul.min'>;
}
declare module 'hangul-js/test/index.js' {
  declare module.exports: $Exports<'hangul-js/test/index'>;
}
declare module 'hangul-js/test/server-side.js' {
  declare module.exports: $Exports<'hangul-js/test/server-side'>;
}
