// flow-typed signature: 5366415bb91494b8f039dcb04191d974
// flow-typed version: <<STUB>>/react-form_v^1.3.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-form/lib/form' {
  declare module.exports: any;
}

declare module 'react-form/lib/formError' {
  declare module.exports: any;
}

declare module 'react-form/lib/formField' {
  declare module.exports: any;
}

declare module 'react-form/lib/formInput' {
  declare module.exports: any;
}

declare module 'react-form/lib/formInputs/checkbox' {
  declare module.exports: any;
}

declare module 'react-form/lib/formInputs/form' {
  declare module.exports: any;
}

declare module 'react-form/lib/formInputs/nestedForm' {
  declare module.exports: any;
}

declare module 'react-form/lib/formInputs/radio' {
  declare module.exports: any;
}

declare module 'react-form/lib/formInputs/radioGroup' {
  declare module.exports: any;
}

declare module 'react-form/lib/formInputs/select' {
  declare module.exports: any;
}

declare module 'react-form/lib/formInputs/text' {
  declare module.exports: any;
}

declare module 'react-form/lib/formInputs/textarea' {
  declare module.exports: any;
}

declare module 'react-form/lib/formInputs/util' {
  declare module.exports: any;
}

declare module 'react-form/lib/index' {
  declare module.exports: any;
}

declare module 'react-form/lib/utils' {
  declare module.exports: any;
}

declare module 'react-form/react-form' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-form/lib/form.js' {
  declare module.exports: $Exports<'react-form/lib/form'>;
}
declare module 'react-form/lib/formError.js' {
  declare module.exports: $Exports<'react-form/lib/formError'>;
}
declare module 'react-form/lib/formField.js' {
  declare module.exports: $Exports<'react-form/lib/formField'>;
}
declare module 'react-form/lib/formInput.js' {
  declare module.exports: $Exports<'react-form/lib/formInput'>;
}
declare module 'react-form/lib/formInputs/checkbox.js' {
  declare module.exports: $Exports<'react-form/lib/formInputs/checkbox'>;
}
declare module 'react-form/lib/formInputs/form.js' {
  declare module.exports: $Exports<'react-form/lib/formInputs/form'>;
}
declare module 'react-form/lib/formInputs/nestedForm.js' {
  declare module.exports: $Exports<'react-form/lib/formInputs/nestedForm'>;
}
declare module 'react-form/lib/formInputs/radio.js' {
  declare module.exports: $Exports<'react-form/lib/formInputs/radio'>;
}
declare module 'react-form/lib/formInputs/radioGroup.js' {
  declare module.exports: $Exports<'react-form/lib/formInputs/radioGroup'>;
}
declare module 'react-form/lib/formInputs/select.js' {
  declare module.exports: $Exports<'react-form/lib/formInputs/select'>;
}
declare module 'react-form/lib/formInputs/text.js' {
  declare module.exports: $Exports<'react-form/lib/formInputs/text'>;
}
declare module 'react-form/lib/formInputs/textarea.js' {
  declare module.exports: $Exports<'react-form/lib/formInputs/textarea'>;
}
declare module 'react-form/lib/formInputs/util.js' {
  declare module.exports: $Exports<'react-form/lib/formInputs/util'>;
}
declare module 'react-form/lib/index.js' {
  declare module.exports: $Exports<'react-form/lib/index'>;
}
declare module 'react-form/lib/utils.js' {
  declare module.exports: $Exports<'react-form/lib/utils'>;
}
declare module 'react-form/react-form.js' {
  declare module.exports: $Exports<'react-form/react-form'>;
}
