// flow-typed signature: 23adf1cc2436c7e043e1c65ded9e91f5
// flow-typed version: <<STUB>>/react-styled-tag_v^0.9.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-styled-tag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-styled-tag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-styled-tag/dist-modules/ReactTags' {
  declare module.exports: any;
}

declare module 'react-styled-tag/dist-modules/Suggestions' {
  declare module.exports: any;
}

declare module 'react-styled-tag/dist-modules/Tag' {
  declare module.exports: any;
}

declare module 'react-styled-tag/dist/ReactTags.min' {
  declare module.exports: any;
}

declare module 'react-styled-tag/example/main' {
  declare module.exports: any;
}

declare module 'react-styled-tag/example/vendor/JSXTransformer' {
  declare module.exports: any;
}

declare module 'react-styled-tag/example/vendor/ReactDND.min' {
  declare module.exports: any;
}

declare module 'react-styled-tag/lib/ReactTags' {
  declare module.exports: any;
}

declare module 'react-styled-tag/lib/Suggestions' {
  declare module.exports: any;
}

declare module 'react-styled-tag/lib/Tag' {
  declare module.exports: any;
}

declare module 'react-styled-tag/test/reactTags.test' {
  declare module.exports: any;
}

declare module 'react-styled-tag/test/suggestions.test' {
  declare module.exports: any;
}

declare module 'react-styled-tag/test/tag.test' {
  declare module.exports: any;
}

declare module 'react-styled-tag/webpack-dev-server.config' {
  declare module.exports: any;
}

declare module 'react-styled-tag/webpack-production.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-styled-tag/dist-modules/ReactTags.js' {
  declare module.exports: $Exports<'react-styled-tag/dist-modules/ReactTags'>;
}
declare module 'react-styled-tag/dist-modules/Suggestions.js' {
  declare module.exports: $Exports<'react-styled-tag/dist-modules/Suggestions'>;
}
declare module 'react-styled-tag/dist-modules/Tag.js' {
  declare module.exports: $Exports<'react-styled-tag/dist-modules/Tag'>;
}
declare module 'react-styled-tag/dist/ReactTags.min.js' {
  declare module.exports: $Exports<'react-styled-tag/dist/ReactTags.min'>;
}
declare module 'react-styled-tag/example/main.js' {
  declare module.exports: $Exports<'react-styled-tag/example/main'>;
}
declare module 'react-styled-tag/example/vendor/JSXTransformer.js' {
  declare module.exports: $Exports<'react-styled-tag/example/vendor/JSXTransformer'>;
}
declare module 'react-styled-tag/example/vendor/ReactDND.min.js' {
  declare module.exports: $Exports<'react-styled-tag/example/vendor/ReactDND.min'>;
}
declare module 'react-styled-tag/lib/ReactTags.js' {
  declare module.exports: $Exports<'react-styled-tag/lib/ReactTags'>;
}
declare module 'react-styled-tag/lib/Suggestions.js' {
  declare module.exports: $Exports<'react-styled-tag/lib/Suggestions'>;
}
declare module 'react-styled-tag/lib/Tag.js' {
  declare module.exports: $Exports<'react-styled-tag/lib/Tag'>;
}
declare module 'react-styled-tag/test/reactTags.test.js' {
  declare module.exports: $Exports<'react-styled-tag/test/reactTags.test'>;
}
declare module 'react-styled-tag/test/suggestions.test.js' {
  declare module.exports: $Exports<'react-styled-tag/test/suggestions.test'>;
}
declare module 'react-styled-tag/test/tag.test.js' {
  declare module.exports: $Exports<'react-styled-tag/test/tag.test'>;
}
declare module 'react-styled-tag/webpack-dev-server.config.js' {
  declare module.exports: $Exports<'react-styled-tag/webpack-dev-server.config'>;
}
declare module 'react-styled-tag/webpack-production.config.js' {
  declare module.exports: $Exports<'react-styled-tag/webpack-production.config'>;
}
