/* ----------  USER  ----------*/
export const USER_LOGIN = 'USER_LOGIN';
export const USER_NAME_INJECT = 'USER_NAME_INJECT';

/* ----------  APP  ----------*/
export const CHANGE_FULL_SCREEN = 'CHANGE_FULL_SCREEN';
export const CHANGE_LEFT_BAR = 'CHANGE_LEFT_BAR';
export const CHANGE_RENDER_TAGS = 'CHANGE_RENDER_TAGS';
export const CHANGE_TIMELINE_LEFT_BAR_TAGS = 'CHANGE_TIMELINE_LEFT_BAR_TAGS';
export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
export const CHANGE_NOTE_PREVEW_SORT = 'CHANGE_NOTE_PREVEW_SORT';

/* ---------- NOTE -----------*/
export const SAVE_REQUEST = 'SAVE_REQUEST';
export const SAVE_COMPLETE = 'SAVE_COMPLETE';
export const SAVE_REQUEST_CANCELLED = 'SAVE_REQUEST_CANCELLED';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_COMPLETE = 'DELETE_COMPLETE';
export const CHANGE_TRASH_BOX_ON = 'CHANGE_TRASH_BOX_ON';
