/* ----------  USER  ----------*/
export const USER_LOGIN = 'USER_LOGIN';
export const USER_NAME_INJECT = 'USER_NAME_INJECT';

/* ----------  APP  ----------*/
export const CHANGE_FULL_SCREEN = 'CHANGE_FULL_SCREEN';
export const CHANGE_LEFT_BAR = 'CHANGE_LEFT_BAR';
export const CHANGE_RENDER_TAGS = 'CHANGE_RENDER_TAGS';
export const CHANGE_TIMELINE_LEFT_BAR_TAGS = 'CHANGE_TIMELINE_LEFT_BAR_TAGS';

/* ---------- NOTE -----------*/
export const SAVE_REQUEST = 'SAVE_REQUEST';
export const SAVE_PROGRESS = 'SAVE_PROGRESS';
export const SAVE_COMPLETE = 'SAVE_COMPLETE';
export const MAKE_NEW_REQUEST = 'MAKE_NEW_REQUEST';
export const MAKE_NEW_COMPLETE = 'MAKE_NEW_COMPLETE';
export const THEME_SAVE_CLICK = 'THEME_SAVE_CLICK';
export const THEME_SAVE_REQUEST = 'THEME_SAVE_REQUEST';
export const THEME_SAVE_COMPLETE = 'THEME_SAVE_COMPLETE';
export const CHANGE_NOTE_ID = 'CHANGE_NOTE_ID';
export const NOTE_SHOW_CHANGE = 'NOTE_SHOW_CHANGE';
export const CHANGE_NOTE_ID_AND_NOTE_SHOW_CHANGE = 'CHANGE_NOTE_ID_AND_NOTE_SHOW_CHANGE';
